### ISSUE TITLE
when i python eval.py  ，ValueError: not enough values to unpack (expected 5, got 4)happened

### ISSUE THREAD

**Issue by pussinmood** [jiajingk/train_vima#1]
pybullet build time: Nov 28 2023 23:52:03
[INFO] 17 tasks loaded
/home/fb/anaconda3/envs/vime/lib/python3.9/site-packages/gym/spaces/box.py:127: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
text argument:/home/fb/Downloads/train_vima-main/vima_bench/tasks/assets
  0%|                                                                                                                                     | 0/100 [00:00<?, ?it/s]  0%|                                                                                                                                     | 0/100 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/home/fb/Downloads/train_vima-main/eval.py", line 286, in <module>
    eval_placement_generalization(
  File "/home/fb/anaconda3/envs/vime/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/fb/Downloads/train_vima-main/eval.py", line 258, in eval_placement_generalization
    obs, _, done, info = env.step(policy_action)
  File "/home/fb/anaconda3/envs/vime/lib/python3.9/site-packages/gym/wrappers/time_limit.py", line 50, in step
    observation, reward, terminated, truncated, info = self.env.step(action)
ValueError: not enough values to unpack (expected 5, got 4)

**Comment by jiajingk** [comment]
I couldn't reproduce your issue. It's probably because `gym` version is not matched. You may try setup your environment like [here](https://github.com/jiajingk/train_vima/blob/main/remote_control/vima_code_install.sh).

**Comment by pussinmood** [comment]
thank you ，i ‘l try your way

**Comment by pussinmood** [comment]
problem solved ，thanks again for your help
